### ISSUE TITLE
New Connection - Invalid protocol version: 71

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [sysdream/ligolo#11]
Hey,

I just faced the weird behaviour, that when using the ligolo Client from a Host with direct internet access it works as expected, but when a firewall/proxy of the network is in between i get the following error:

```
INFO[0398] New relay connection.                         remoteaddr="x.x.x.x:33868"
2022/08/29 12:43:27 [ERR] yamux: Invalid protocol version: 71

```

Some idea what the cause could be and how to avoid this to still get an incoming connection? 

Greetings

**Comment by nicocha30** [comment]
Hey!

Do you have more details to share about the firewall/proxy? (Appliance, version). Is it a transparent proxy?

Thanks!

Nicolas.

**Comment by nicocha30** [comment]
Btw, this project is no more maintained. I no longer have access to it since my previous company kicked me from this repository.

Consider using https://github.com/nicocha30/ligolo-ng instead 😉

**Comment by S3cur3Th1sSh1t** [comment]
Can’t tell about which appliance is in place there unfortunately. I think some Sophos firewall but I’m not 100% sure. I’ll close this issue than and switch it to the other repo if that has the same problem 👍
