### ISSUE TITLE
TLS Fingerprint is missing

### ISSUE THREAD

**Issue by fasdfx** [sysdream/ligolo#7]
hi~ guys, I'v got a problem when i use ligolo to connect my server, it said that "TLS Fingerprint is missing" it means that when i use the option '-skipverify' if it means the connection wont be encrypted?

**Comment by nicocha30** [comment]
Hi,

How did you build ligolo?

`skipverify` means `do not validate the remote certificate`. The connection will still be encrypted, however there is a risk of man in the middle attacks.

**Comment by fasdfx** [comment]
cooooollll ! I'll built it in another env, thks a lot~~
